Vagrant.configure("2") do |config|
    config.vm.box = "generic/centos7"
    config.vm.define "oxidebpf-builder-centos-7"
    config.vm.synced_folder "../../", "/home/vagrant/oxidebpf"
    config.vm.provision :shell, path: "bootstrap.sh"
    config.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "8192"
        v.vmx["numvcpus"] = "6"
        v.vmx["ethernet0.pcislotnumber"] = "32"
    end
end